name: TestWorkflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  VAR0: variable_at_workflow_level

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_VAR1: ${{ secrets.SECRET_VAR1 }}

    steps:
      - uses: actions/checkout@v3
      - name: show variables
        env:
          SECRET_VAR2: ${{ secrets.SECRET_VAR2 }}
        run: |
          echo "env1: ${{ env.VAR1 }}"
          echo "value1: ${{ env.SECRET_VAR1 }}"
          echo "value2: ${{ env.SECRET_VAR2 }}"
          if [ $SECRET_VAR1 == $SECRET_VAR] ; then echo same ; else echo differ ; fi
