name: TestWorkflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VAR1: ${{ secrets.VAR1 }}

    steps:
      - uses: actions/checkout@v3
      - name: show variables
        env:
          VAR2: ${{ secrets.VAR2 }}
        run: |
          echo "value1: ${{ env.VAR1 }}"
          echo "value2: ${{ env.VAR2 }}"
