#
# sample workflow to demonstrate different ways for providing environment values
# 
# documentation:
#  - https://docs.github.com/en/actions/learn-github-actions/environment-variables
#  - https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment

# scopes for variables:
# ---------------------
#
# a) global - for the workflow
# b) local - for a specific job
# c) local - for a specific step in a specific job

# sources for variables:
# ----------------------
#
# a) specify directly in workflow definition (this file)
# b) via environment secrets
#    - https://github.com/<...>/settings/environments
#    - must specify environment in workflow
# c) via repository secrets
#    - https://github.com/<...>/settings/secrets/actions

name: TestWorkflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  VAR0: hardcoded_at_workflow_level

jobs:
  build:
    runs-on: ubuntu-latest

    # required setting for b)
    environment:
      # create an environment with name 'variables for master'
      # https://github.com/<username>/<repositor>/settings/environments
      name: variables for master
      url: https://link-to-documentation-page.invalid/

    env:
      VAR1E: ${{ secrets.ENV_VAR1 }}
      VAR1R: ${{ secrets.SECRET_VAR1 }}
      COND: ${{ secrets.TRUE }}

    steps:
      - uses: actions/checkout@v3
      - name: show variables
        env:
          VAR2E: ${{ secrets.ENV_VAR2 }}
          VAR2R: ${{ secrets.SECRET_VAR2 }}
        run: |
          echo "var0: $VAR0"
          echo "var1 (env):  $VAR1E"
          echo "var1 (repo): ${{ env.VAR1R }}"
          echo "conditional: $COND"
          echo "var2: $VAR2E"
          echo "var2: $VAR2R"
          if [ "x$VAR1R" == "x$VAR2R" ] ; then echo same ; else echo differ ; fi
      - name: conditional step
        if: ${{ env.COND == 'true' }}
        run: echo "triggered conditional step"
